[profile.default]
#out = "artifacts"
#src = "src"
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = ["@openzeppelin/=node_modules/@openzeppelin/"]
allow_paths = ["../../node_modules"]
auto_detect_solc = true
cache_path  = "cache_forge"
test = "test"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
