[profile.default]
#solc = "0.8.20"
auto_detect_solc = true
src = "contracts"
out = "artifacts"
#src = "src"
#out = "out"
libs = ["lib"]
#libs = ["node_modules", "lib"]
#remappings = ["@openzeppelin/=node_modules/@openzeppelin/"]
#allow_paths = ["../../node_modules"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
